export const KEYS = {
  AUTH_LOGIN: '/auth/login',
  AUTH_GOOGLE: '/auth/google',
  AUTH_REGISTER: '/auth/register',
  AUTH_ME: '/auth/me',
  AUTH_PROFILE: '/auth/profile',
  AUTH_PROFILE_AVATAR: '/auth/profile/avatar',
  AUTH_PASSWORD: '/auth/password',
  AUTH_LOGOUT: '/auth/logout',
  OTP_VERIFY_REGISTER: '/otp/verify-register',
  OTP_FORGOT_PASSWORD: '/otp/forgot-password',
  OTP_RESEND: '/otp/resend',
  AUTH_RESET_PASSWORD: '/auth/reset-password',
  TOKEN_REFRESH: '/token/refresh',
  TOKEN_REVOKE: '/token/revoke',
} as const;
