import type { CartLineInput } from "@/apis/cart/types";
import type { ProductCatalogItem } from "@/types/catalog";
import { productImage } from "@/lib/product-images";

export const PRODUCT_CATALOG: ProductCatalogItem[] = [
  {
    productId: "mock-ip15p-256",
    name: "iPhone 15 Pro 256GB",
    categoryId: "cat-apple",
    category: "iPhone & Apple",
    vendor: "Apple Store VN",
    price: 28_990_000,
    originalPrice: 31_990_000,
    image: productImage("phone"),
    rating: 4.8,
    badge: "-9%",
  },
  {
    productId: "mock-ip15-128",
    name: "iPhone 15 128GB",
    categoryId: "cat-apple",
    category: "iPhone & Apple",
    vendor: "Apple Store VN",
    price: 22_990_000,
    originalPrice: 24_990_000,
    image: productImage("phoneAlt"),
    rating: 4.7,
    badge: "Hot",
  },
  {
    productId: "mock-ip14-256",
    name: "iPhone 14 256GB",
    categoryId: "cat-apple",
    category: "iPhone & Apple",
    vendor: "TechZone",
    price: 18_990_000,
    originalPrice: 21_490_000,
    image: productImage("phoneDark"),
    rating: 4.6,
    badge: "Sale",
  },
  {
    productId: "mock-s24u-512",
    name: "Samsung Galaxy S24 Ultra 512GB",
    categoryId: "cat-samsung",
    category: "Samsung Galaxy",
    vendor: "Samsung Hub",
    price: 29_490_000,
    originalPrice: 32_990_000,
    image: productImage("phoneDark"),
    rating: 4.9,
    badge: "-11%",
  },
  {
    productId: "mock-s24-256",
    name: "Samsung Galaxy S24 256GB",
    categoryId: "cat-samsung",
    category: "Samsung Galaxy",
    vendor: "Samsung Hub",
    price: 19_990_000,
    originalPrice: 22_490_000,
    image: productImage("phoneAlt"),
    rating: 4.7,
    badge: "Hot",
  },
  {
    productId: "mock-zflip6",
    name: "Samsung Galaxy Z Flip6",
    categoryId: "cat-samsung",
    category: "Samsung Galaxy",
    vendor: "Samsung Hub",
    price: 24_990_000,
    image: productImage("phone"),
    rating: 4.5,
    badge: "New",
  },
  {
    productId: "mock-pixel9-128",
    name: "Google Pixel 9 128GB",
    categoryId: "cat-google",
    category: "Google Pixel",
    vendor: "Google Official",
    price: 18_990_000,
    originalPrice: 20_990_000,
    image: productImage("phoneAlt"),
    rating: 4.6,
    badge: "-10%",
  },
  {
    productId: "mock-pixel8pro",
    name: "Google Pixel 8 Pro",
    categoryId: "cat-google",
    category: "Google Pixel",
    vendor: "Google Official",
    price: 16_490_000,
    originalPrice: 19_990_000,
    image: productImage("phone"),
    rating: 4.5,
    badge: "Sale",
  },
  {
    productId: "mock-xiaomi14-512",
    name: "Xiaomi 14 512GB",
    categoryId: "cat-xiaomi",
    category: "Xiaomi",
    vendor: "Xiaomi Store",
    price: 16_990_000,
    originalPrice: 18_990_000,
    image: productImage("phone"),
    rating: 4.7,
    badge: "-11%",
  },
  {
    productId: "mock-xiaomi14t",
    name: "Xiaomi 14T Pro",
    categoryId: "cat-xiaomi",
    category: "Xiaomi",
    vendor: "Xiaomi Store",
    price: 14_990_000,
    image: productImage("phoneAlt"),
    rating: 4.6,
    badge: "Hot",
  },
  {
    productId: "mock-ipad-air",
    name: "iPad Air M2 256GB",
    categoryId: "cat-tablet",
    category: "Tablet",
    vendor: "Apple Store VN",
    price: 19_990_000,
    originalPrice: 22_490_000,
    image: productImage("tablet"),
    rating: 4.8,
    badge: "Sale",
  },
  {
    productId: "mock-tab-s9",
    name: "Galaxy Tab S9",
    categoryId: "cat-tablet",
    category: "Tablet",
    vendor: "Samsung Hub",
    price: 17_490_000,
    image: productImage("tablet"),
    rating: 4.5,
  },
  {
    productId: "mock-watch-ultra",
    name: "Apple Watch Ultra 2",
    categoryId: "cat-watch",
    category: "Đồng hồ thông minh",
    vendor: "Apple Store VN",
    price: 21_990_000,
    originalPrice: 23_990_000,
    image: productImage("watch"),
    rating: 4.9,
    badge: "-8%",
  },
  {
    productId: "mock-watch-gw6",
    name: "Galaxy Watch6 Classic",
    categoryId: "cat-watch",
    category: "Đồng hồ thông minh",
    vendor: "Samsung Hub",
    price: 8_990_000,
    image: productImage("watch"),
    rating: 4.6,
    badge: "New",
  },
  {
    productId: "mock-airpods-pro",
    name: "AirPods Pro 2 USB-C",
    categoryId: "cat-audio",
    category: "Tai nghe & Loa",
    vendor: "Apple Store VN",
    price: 5_990_000,
    originalPrice: 6_990_000,
    image: productImage("audio"),
    rating: 4.8,
    badge: "-14%",
  },
  {
    productId: "mock-buds3pro",
    name: "Galaxy Buds3 Pro",
    categoryId: "cat-audio",
    category: "Tai nghe & Loa",
    vendor: "Samsung Hub",
    price: 4_490_000,
    image: productImage("audio"),
    rating: 4.5,
    badge: "Hot",
  },
  {
    productId: "mock-magsafe",
    name: "Sạc MagSafe 15W",
    categoryId: "cat-charger",
    category: "Sạc & Cáp",
    vendor: "TechZone",
    price: 1_290_000,
    originalPrice: 1_590_000,
    image: productImage("charger"),
    rating: 4.4,
    badge: "Sale",
  },
  {
    productId: "mock-cable-usbc",
    name: "Cáp USB-C 100W 2m",
    categoryId: "cat-charger",
    category: "Sạc & Cáp",
    vendor: "Anker VN",
    price: 390_000,
    image: productImage("charger"),
    rating: 4.3,
  },
  {
    productId: "mock-case-ip15",
    name: "Ốp lưng iPhone 15 Pro",
    categoryId: "cat-case",
    category: "Ốp lưng",
    vendor: "Spigen VN",
    price: 590_000,
    originalPrice: 790_000,
    image: productImage("case"),
    rating: 4.5,
    badge: "-25%",
  },
  {
    productId: "mock-case-s24",
    name: "Ốp lưng Galaxy S24",
    categoryId: "cat-case",
    category: "Ốp lưng",
    vendor: "Spigen VN",
    price: 490_000,
    image: productImage("case"),
    rating: 4.4,
  },
];

export const MOCK_PRODUCTS: CartLineInput[] = PRODUCT_CATALOG.map((p) => ({
  productId: p.productId,
  name: p.name,
  price: p.price,
  quantity: 1,
  image: p.image,
}));
