import { MOCK_PRODUCTS } from "@/faker/mock-products"
import {
  LoaiBienDongKho,
  type ILichSuKho,
  type IPhieuNhapKho,
  type IPhienKiemKho,
  type ITonKhoSanPham,
  type INhaCungCap,
} from "@/features/inventory/types"

const now = "2024-05-16T10:00:00Z"

export const MOCK_TON_KHO: ITonKhoSanPham[] = [
  {
    id: "tk-1",
    productId: MOCK_PRODUCTS[0]!.productId,
    tenSanPham: MOCK_PRODUCTS[0]!.name,
    bienThe: "256GB · Titan tự nhiên",
    sku: "IP15P-256-TN",
    anh: MOCK_PRODUCTS[0]!.image,
    tonKhaDung: 86,
    dangGiu: 12,
    daBan: 420,
    soLuongHoanTra: 0,
    nguongCanhBao: 20,
    capNhatLuc: now,
  },
  {
    id: "tk-2",
    productId: MOCK_PRODUCTS[0]!.productId,
    tenSanPham: MOCK_PRODUCTS[0]!.name,
    bienThe: "512GB · Titan đen",
    sku: "IP15P-512-BK",
    anh: MOCK_PRODUCTS[0]!.image,
    tonKhaDung: 8,
    dangGiu: 4,
    daBan: 210,
    soLuongHoanTra: 0,
    nguongCanhBao: 15,
    capNhatLuc: now,
  },
  {
    id: "tk-3",
    productId: MOCK_PRODUCTS[1]!.productId,
    tenSanPham: MOCK_PRODUCTS[1]!.name,
    bienThe: "512GB · Titanium Gray",
    sku: "S24U-512-TG",
    anh: MOCK_PRODUCTS[1]!.image,
    tonKhaDung: 45,
    dangGiu: 6,
    daBan: 380,
    soLuongHoanTra: 0,
    nguongCanhBao: 25,
    capNhatLuc: now,
  },
  {
    id: "tk-4",
    productId: MOCK_PRODUCTS[2]!.productId,
    tenSanPham: MOCK_PRODUCTS[2]!.name,
    bienThe: "128GB · Obsidian",
    sku: "PIX9-128-OB",
    anh: MOCK_PRODUCTS[2]!.image,
    tonKhaDung: 0,
    dangGiu: 0,
    daBan: 156,
    soLuongHoanTra: 0,
    nguongCanhBao: 10,
    capNhatLuc: now,
  },
  {
    id: "tk-5",
    productId: MOCK_PRODUCTS[3]!.productId,
    tenSanPham: MOCK_PRODUCTS[3]!.name,
    bienThe: "512GB · Đen",
    sku: "XM14-512-BK",
    anh: MOCK_PRODUCTS[3]!.image,
    tonKhaDung: 14,
    dangGiu: 2,
    daBan: 98,
    soLuongHoanTra: 0,
    nguongCanhBao: 15,
    capNhatLuc: now,
    tonLauNgay: true,
  },
  {
    id: "tk-6",
    productId: MOCK_PRODUCTS[1]!.productId,
    tenSanPham: MOCK_PRODUCTS[1]!.name,
    bienThe: "256GB · Onyx Black",
    sku: "S24U-256-OB",
    anh: MOCK_PRODUCTS[1]!.image,
    tonKhaDung: 3,
    dangGiu: 1,
    daBan: 502,
    soLuongHoanTra: 0,
    nguongCanhBao: 20,
    capNhatLuc: now,
    tonLauNgay: true,
  },
]

export const MOCK_LICH_SU_KHO: ILichSuKho[] = [
  {
    id: "mv-1",
    thoiGian: "2024-05-16T09:12:00Z",
    tonKhoId: "tk-1",
    tenSanPham: MOCK_TON_KHO[0]!.tenSanPham,
    sku: MOCK_TON_KHO[0]!.sku,
    loai: LoaiBienDongKho.NHAP_KHO,
    soLuong: 50,
    truocThayDoi: 36,
    sauThayDoi: 86,
    ghiChu: "Nhập từ NCC FPT",
    nguoiThaoTac: "Nguyễn Minh Anh",
  },
  {
    id: "mv-2",
    thoiGian: "2024-05-16T08:40:00Z",
    tonKhoId: "tk-3",
    tenSanPham: MOCK_TON_KHO[2]!.tenSanPham,
    sku: MOCK_TON_KHO[2]!.sku,
    loai: LoaiBienDongKho.GIU_HANG,
    soLuong: 2,
    truocThayDoi: 47,
    sauThayDoi: 45,
    ghiChu: "Giữ hàng đơn ORD-X9Y8Z7",
    nguoiThaoTac: "Hệ thống",
  },
  {
    id: "mv-3",
    thoiGian: "2024-05-15T16:20:00Z",
    tonKhoId: "tk-4",
    tenSanPham: MOCK_TON_KHO[3]!.tenSanPham,
    sku: MOCK_TON_KHO[3]!.sku,
    loai: LoaiBienDongKho.BAN_HANG,
    soLuong: 5,
    truocThayDoi: 5,
    sauThayDoi: 0,
    ghiChu: "Hoàn tất đơn ORD-A1B2C3",
    nguoiThaoTac: "Hệ thống",
  },
  {
    id: "mv-4",
    thoiGian: "2024-05-15T11:05:00Z",
    tonKhoId: "tk-2",
    tenSanPham: MOCK_TON_KHO[1]!.tenSanPham,
    sku: MOCK_TON_KHO[1]!.sku,
    loai: LoaiBienDongKho.DIEU_CHINH,
    soLuong: -2,
    truocThayDoi: 10,
    sauThayDoi: 8,
    ghiChu: "Hàng lỗi phát hiện khi kiểm kho",
    nguoiThaoTac: "Nguyễn Minh Anh",
  },
]

export const MOCK_PHIEU_NHAP: IPhieuNhapKho[] = [
  {
    id: "pn-1",
    maPhieu: "PN-20240516-001",
    nhaCungCap: "FPT Distribution",
    ngayNhap: "2024-05-16",
    ghiChu: "Nhập hàng tuần",
    nguoiTao: "Nguyễn Minh Anh",
    chiTiet: [
      { id: "ct-1", tonKhoId: "tk-1", tenSanPham: "iPhone 15 Pro 256GB", sku: "IP15P-256-TN", soLuong: 50 },
      { id: "ct-2", tonKhoId: "tk-3", tenSanPham: "Samsung Galaxy S24 Ultra 512GB", sku: "S24U-512-TG", soLuong: 30 },
    ],
  },
]

export const MOCK_PHIEN_KIEM: IPhienKiemKho[] = [
  {
    id: "pk-1",
    maPhien: "KK-20240515-01",
    tonKhoId: "tk-2",
    tenSanPham: MOCK_TON_KHO[1]!.tenSanPham,
    sku: MOCK_TON_KHO[1]!.sku,
    heThong: 10,
    thucTe: 8,
    chenhLech: -2,
    thoiGian: "2024-05-15T11:00:00Z",
    nguoiKiem: "Nguyễn Minh Anh",
  },
]

export const MOCK_NHA_CUNG_CAP: INhaCungCap[] = [
  {
    id: "ncc-1",
    ten: "FPT Distribution",
    anh: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&h=100&fit=crop",
    sdt: "024 7300 6600",
    email: "fpt.distribution@fpt.com.vn",
    diaChi: "Tòa nhà FPT, Phố Duy Tân, Cầu Giấy, Hà Nội",
  },
  {
    id: "ncc-2",
    ten: "Digiworld Corporation",
    anh: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&h=100&fit=crop",
    sdt: "028 3929 0808",
    email: "info@digiworld.com.vn",
    diaChi: "195-197 Cao Thắng, Phường 12, Quận 10, TP.HCM",
  },
  {
    id: "ncc-3",
    ten: "Petrosetco (PSD)",
    anh: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=100&h=100&fit=crop",
    sdt: "028 3911 5578",
    email: "contact@psd.com.vn",
    diaChi: "Lầu 6, Tòa nhà Petroland, 12 Tân Trào, Quận 7, TP.HCM",
  },
  {
    id: "ncc-4",
    ten: "Apple Vietnam",
    anh: "https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=100&h=100&fit=crop",
    sdt: "1800 1127",
    email: "support@apple.com.vn",
    diaChi: "Tòa nhà Deutsches Haus, 33 Lê Duẩn, Quận 1, TP.HCM",
  },
  {
    id: "ncc-5",
    ten: "Samsung Electronics Vietnam",
    anh: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop",
    sdt: "1800 588 889",
    email: "sales.sevc@samsung.com",
    diaChi: "Khu công nghiệp Yên Phong, Yên Trung, Yên Phong, Bắc Ninh",
  },
]
